name: Build and Deploy MAUI App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Install .NET MAUI workload
      run: dotnet workload install maui


    - name: Build and Publish MAUI App
      run: |
        dotnet restore
        dotnet build -c Release
        dotnet publish -c Release -o out

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
